/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user?: NexusGenRootTypes['User'] | null; // User
  }
  BadRequest: { // root type
    errorMessage: string; // String!
    errorType: string; // String!
  }
  Card: { // root type
    back: string; // String!
    creator?: NexusGenRootTypes['User'] | null; // User
    creatorId: number; // Int!
    front: string; // String!
    id: number; // Int!
    isPublic: boolean; // Boolean!
    topic: string; // String!
  }
  DataNotFound: { // root type
    errorMessage: string; // String!
    errorType: string; // String!
  }
  Mutation: {};
  NoAccess: { // root type
    errorMessage: string; // String!
    errorType: string; // String!
  }
  NotLoggedIn: { // root type
    errorMessage: string; // String!
    errorType: string; // String!
  }
  Query: {};
  User: { // root type
    email: string; // String!
    id: number; // Int!
    names: string; // String!
    password: string; // String!
  }
}

export interface NexusGenInterfaces {
  Error: NexusGenRootTypes['BadRequest'] | NexusGenRootTypes['DataNotFound'] | NexusGenRootTypes['NoAccess'] | NexusGenRootTypes['NotLoggedIn'];
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User'] | null; // User
  }
  BadRequest: { // field return type
    errorMessage: string; // String!
    errorType: string; // String!
  }
  Card: { // field return type
    back: string; // String!
    creator: NexusGenRootTypes['User'] | null; // User
    creatorId: number; // Int!
    front: string; // String!
    id: number; // Int!
    isPublic: boolean; // Boolean!
    topic: string; // String!
  }
  DataNotFound: { // field return type
    errorMessage: string; // String!
    errorType: string; // String!
  }
  Mutation: { // field return type
    createNewCard: NexusGenRootTypes['Card']; // Card!
    deleteCard: boolean; // Boolean!
    deleteUser: boolean; // Boolean!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signUp: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    updateCard: NexusGenRootTypes['Card']; // Card!
    updateUser: NexusGenRootTypes['User']; // User!
  }
  NoAccess: { // field return type
    errorMessage: string; // String!
    errorType: string; // String!
  }
  NotLoggedIn: { // field return type
    errorMessage: string; // String!
    errorType: string; // String!
  }
  Query: { // field return type
    allUsers: NexusGenRootTypes['User'][]; // [User!]!
    publicCards: NexusGenRootTypes['Card'][]; // [Card!]!
    userOwnCards: NexusGenRootTypes['Query'][]; // [Query!]!
  }
  User: { // field return type
    email: string; // String!
    id: number; // Int!
    names: string; // String!
    password: string; // String!
  }
  Error: { // field return type
    errorMessage: string; // String!
    errorType: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  BadRequest: { // field return type name
    errorMessage: 'String'
    errorType: 'String'
  }
  Card: { // field return type name
    back: 'String'
    creator: 'User'
    creatorId: 'Int'
    front: 'String'
    id: 'Int'
    isPublic: 'Boolean'
    topic: 'String'
  }
  DataNotFound: { // field return type name
    errorMessage: 'String'
    errorType: 'String'
  }
  Mutation: { // field return type name
    createNewCard: 'Card'
    deleteCard: 'Boolean'
    deleteUser: 'Boolean'
    login: 'AuthPayload'
    signUp: 'AuthPayload'
    updateCard: 'Card'
    updateUser: 'User'
  }
  NoAccess: { // field return type name
    errorMessage: 'String'
    errorType: 'String'
  }
  NotLoggedIn: { // field return type name
    errorMessage: 'String'
    errorType: 'String'
  }
  Query: { // field return type name
    allUsers: 'User'
    publicCards: 'Card'
    userOwnCards: 'Query'
  }
  User: { // field return type name
    email: 'String'
    id: 'Int'
    names: 'String'
    password: 'String'
  }
  Error: { // field return type name
    errorMessage: 'String'
    errorType: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createNewCard: { // args
      back: string; // String!
      front: string; // String!
      isPublic: boolean; // Boolean!
      topic: string; // String!
    }
    deleteCard: { // args
      id: number; // Int!
    }
    deleteUser: { // args
      id: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    signUp: { // args
      email: string; // String!
      names: string; // String!
      password: string; // String!
    }
    updateCard: { // args
      back?: string | null; // String
      front?: string | null; // String
      id: number; // Int!
      isPublic?: string | null; // String
      topic?: string | null; // String
    }
    updateUser: { // args
      email?: string | null; // String
      id: number; // Int!
      password?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  Error: "BadRequest" | "DataNotFound" | "NoAccess" | "NotLoggedIn"
}

export interface NexusGenTypeInterfaces {
  BadRequest: "Error"
  DataNotFound: "Error"
  NoAccess: "Error"
  NotLoggedIn: "Error"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    resolveType: false
    __typename: false
    isTypeOf: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}