name: Deploy
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - name: Check lint errors
        run: yarn run lint
      - name: Check build success
        run: yarn build
  deploy:
    concurrency:
      group: heroku_deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: development
    needs: [build]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Deploy to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'megamind-flashcards'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
