name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Deploy to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'megamind-flashcards'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
